### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by developeromI89** [googlesamples/android-play-location#104]
Getting two issues when running on Android Lollipop
1.Received call to unregister a listener without a matching registration call.
                                                                                            java.lang.Exception
                                                                                                at com.google.android.gms.internal.zzbcd.zzb(Unknown Source)
                                                                                                at com.google.android.gms.internal.zzbbz.zza(Unknown Source)
                                                                                                at com.google.android.gms.internal.zzbep.zzb(Unknown Source)
                                                                                                at com.google.android.gms.internal.zzbep.zza(Unknown Source)
                                                                                                at com.google.android.gms.internal.zzben.handleMessage(Unknown Source)
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                                at android.os.Looper.loop(Looper.java:135)
                                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)

2. E/AndroidRuntime: FATAL EXCEPTION: GoogleApiHandler
                                                                                    Process: com.example.admin1.interactivedemo, PID: 15300
                                                                                    java.lang.SecurityException: Client must have ACCESS_FINE_LOCATION permission to request PRIORITY_HIGH_ACCURACY locations.
                                                                                        at android.os.Parcel.readException(Parcel.java:1546)
                                                                                        at android.os.Parcel.readException(Parcel.java:1499)
                                                                                        at com.google.android.gms.internal.zzed.zzb(Unknown Source)
                                                                                        at com.google.android.gms.internal.zzcem.zza(Unknown Source)
                                                                                        at com.google.android.gms.internal.zzcep.zza(Unknown Source)
                                                                                        at com.google.android.gms.internal.zzcev.zza(Unknown Source)
                                                                                        at com.google.android.gms.location.zzg.zzb(Unknown Source)
                                                                                        at com.google.android.gms.internal.zzbcb.zzb(Unknown Source)
                                                                                        at com.google.android.gms.internal.zzbbz.zza(Unknown Source)
                                                                                        at com.google.android.gms.internal.zzbep.zzb(Unknown Source)
                                                                                        at com.google.android.gms.internal.zzbep.zza(Unknown Source)
                                                                                        at com.google.android.gms.internal.zzben.handleMessage(Unknown Source)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Cuke7** [comment]
For the second issue, see : https://github.com/googlesamples/android-play-location/issues/91
