### ISSUE TITLE
App crashes on load

### ISSUE THREAD

**Issue by punitshah89** [googlesamples/android-play-location#43]
I am using https://github.com/googlesamples/android-play-location/tree/master/LocationUpdates Sample project to test whether app can get coordinates or not with only Wi-Fi enabled on Samsung Tab 4. But app crashes always.

I think app crashes because mCurrentLocation is always null when GPS is disabled and Wi-Fi is enabled and connected to active internet connection. Seems like FusedLocationApi failed to get location with just    Wi-Fi enabled. And i think it won't call onLocationChanged() method ever.

It works fine when GPS is enabled.

Device info
Samsung Galaxy Tab® 4 10.1
Android OS: 5.0.2

Stack Trace
_________________________________
FATAL EXCEPTION: main
                                                                                                        Process: com.google.android.gms.location.sample.locationupdates, PID: 20866
                                                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
                                                                                                            at com.google.android.gms.location.sample.locationupdates.MainActivity.updateUI(MainActivity.java:270)
                                                                                                            at com.google.android.gms.location.sample.locationupdates.MainActivity.onConnected(MainActivity.java:344)
                                                                                                            at com.google.android.gms.common.internal.zzk.zzh(Unknown Source)
                                                                                                            at com.google.android.gms.internal.zzlg.zznU(Unknown Source)
                                                                                                            at com.google.android.gms.internal.zzlg.onConnected(Unknown Source)
                                                                                                            at com.google.android.gms.internal.zzli$2.onConnected(Unknown Source)
                                                                                                            at com.google.android.gms.common.internal.zzj$zzg.zzpf(Unknown Source)
                                                                                                            at com.google.android.gms.common.internal.zzj$zza.zzc(Unknown Source)
                                                                                                            at com.google.android.gms.common.internal.zzj$zza.zzt(Unknown Source)
                                                                                                            at com.google.android.gms.common.internal.zzj$zzc.zzph(Unknown Source)
                                                                                                            at com.google.android.gms.common.internal.zzj$zzb.handleMessage(Unknown Source)
                                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                            at android.os.Looper.loop(Looper.java:145)
                                                                                                            at android.app.ActivityThread.main(ActivityThread.java:6134)
                                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by istiak-mlbd** [comment]
same issue facing
